logging:
    level:
        tk.mybatis: DEBUG
        cn.devops: DEBUG
    config: classpath:logback.xml
    path: /jiuke-voicefile

spring:
    application:
        name: jiuke-voicefile
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: voicefile
        url: jdbc:mysql://172.19.70.136:3306/voicefile?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
        username: root
        password: clienT1!
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mail:
        host: smtp.163.com
        username: xxhqa0010@163.com
        password: 42028477xsk
        default: UTF-8
        to: xxhqa0010@163.com
linglian:
    url: http://localhost:10005/test/getUrls
    voicefile:
        filePath: E:/modelFile/model.xls

url:
    prefix: http://xxx/xxx/
